
GET http://localhost:3000/nieistniejaca-sciezka HTTP/1.1

###

GET http://localhost:3000/api/notes HTTP/1.1

###

GET http://localhost:3000/api/notes?search=first&note HTTP/1.1

###

GET http://localhost:3000/api/notes/2 HTTP/1.1

###

GET http://localhost:3000/api/notes/5 HTTP/1.1

###

POST http://localhost:3000/api/notes HTTP/1.1
Content-Type: application/json

{
  "title": "Moja notatka",
  "content": "Treść"
}

###

PUT http://localhost:3000/api/notes/2 HTTP/1.1
Content-Type: application/json

{
  "title": "Zaktualizowany tytuł",
  "content": "Zaktualizowana treść"
}

###

DELETE http://localhost:3000/api/notes/2 HTTP/1.1

###

GET http://localhost:3000/test HTTP/1.1

###

GET http://localhost:3000/api/test-auth HTTP/1.1
X-API-Key: my-secret-key-123